CREATE TABLE IF NOT EXISTS accounts (
  id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  document_number VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS transactions (
  transaction_id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  account_id BIGINT NOT NULL,
  operation_type INT NOT NULL,
  amount DECIMAL(19,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_transaction_account FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
) ENGINE=InnoDB;

